//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR.WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class WindowCommonConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static WindowCommonConfig defaultInstance = ((WindowCommonConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowCommonConfig())));
        
        public static WindowCommonConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double SearchWindowWidth {
            get {
                return ((double)(this["SearchWindowWidth"]));
            }
            set {
                this["SearchWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double SearchWindowHeight {
            get {
                return ((double)(this["SearchWindowHeight"]));
            }
            set {
                this["SearchWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double GridWindowHeight {
            get {
                return ((double)(this["GridWindowHeight"]));
            }
            set {
                this["GridWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double GridWindowWidth {
            get {
                return ((double)(this["GridWindowWidth"]));
            }
            set {
                this["GridWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double TableWindowHeight {
            get {
                return ((double)(this["TableWindowHeight"]));
            }
            set {
                this["TableWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double TableWindowWidth {
            get {
                return ((double)(this["TableWindowWidth"]));
            }
            set {
                this["TableWindowWidth"] = value;
            }
        }
    }
}
